# Generated by Django 3.2.4 on 2021-09-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_alter_pregunta_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Marque la correcta'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='texto',
            field=models.TextField(verbose_name='Escriba la respuesta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Escriba la pregunta'),
        ),
    ]
