# Generated by Django 3.2.4 on 2021-09-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0009_alter_pregunta_max_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es la pregunta correcta?'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=130, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='¿Es la respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje Obtenido'),
        ),
    ]
