# Generated by Django 3.2.4 on 2021-09-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_auto_20210903_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='Cual es la respuesta correcta?'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='texto',
            field=models.TextField(verbose_name='Dice la respuesta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Dice la pregunta'),
        ),
    ]
